- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.3.4
- 🌲 Branch: merge-packages-test-cicd
* checkout-repo ([#109](https://github.com/qlover/fe-base/issues/109)) ([49f7c63](https://github.com/qlover/fe-base/commit/49f7c634b65631bc3d8e9dc577acaf08dc7957d3))
* Revert "build: fe-scripts test 0.3.4 CI (#106)" (#107) ([fc6826a](https://github.com/qlover/fe-base/commit/fc6826ab85d89db770323062b8b13c7aeb93aa57)), closes [#106](https://github.com/qlover/fe-base/issues/106) [#107](https://github.com/qlover/fe-base/issues/107)
> [Test Packages Release] Branch:merge-packages-test-cicd, Tag:0.3.4, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.3.8
* remove auto merge ([#121](https://github.com/qlover/fe-base/issues/121)) ([434b198](https://github.com/qlover/fe-base/commit/434b198e174963c2f683362c22cc5295173a7a63))
* release ignore changelog ([#125](https://github.com/qlover/fe-base/issues/125)) ([d738a72](https://github.com/qlover/fe-base/commit/d738a72875020273401b1bd3b92e1f1108a1e116))
* release push changlog.md ([#123](https://github.com/qlover/fe-base/issues/123)) ([1952ae1](https://github.com/qlover/fe-base/commit/1952ae1caad2a965ec233eca18092bb0b356987b))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.3.8, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.5
* comm commitizen ([#128](https://github.com/qlover/fe-base/issues/128)) ([042ff3a](https://github.com/qlover/fe-base/commit/042ff3a71ab6bec039ee4fa1bc3f4fc116f9dd35))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.5, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.6
* fetchRequest type defined ([#132](https://github.com/qlover/fe-base/issues/132)) ([de0a655](https://github.com/qlover/fe-base/commit/de0a655a9b34c39b1a8932b43c02a27787c4faad))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.6, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.8
* fe code to markdown ([#136](https://github.com/qlover/fe-base/issues/136)) ([f320ccb](https://github.com/qlover/fe-base/commit/f320ccb08d59caabb83357c65a09fb05732cb146))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.8, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.7.1
* remove ConfigSearch,FeScriptContext,ScriptLogger, Shell. use @qlover/script-context ([#223](https://github.com/qlover/fe-base/issues/223)) ([2e07e65](https://github.com/qlover/fe-base/commit/2e07e655ca32d56debe0bb5409958082e32cb1d4))
* script-context merge config ([#224](https://github.com/qlover/fe-base/issues/224)) ([8519dec](https://github.com/qlover/fe-base/commit/8519dec765bf560601c6081ddc5109d4395b6f3d))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.7.1, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 0.1.4
* fe-release publish path ([#231](https://github.com/qlover/fe-base/issues/231)) ([d780b0d](https://github.com/qlover/fe-base/commit/d780b0d0c3c2be2955b31c58eb857e00f3df783a))
* fe-release publish path check ([#236](https://github.com/qlover/fe-base/issues/236)) ([364984e](https://github.com/qlover/fe-base/commit/364984e3b3c27ed3a1e5cd3cc12d3c1184916fab))
* update fe-release version flag ([#256](https://github.com/qlover/fe-base/issues/256)) ([2523f35](https://github.com/qlover/fe-base/commit/2523f3554664a59bd9dc92eb5963e06cebf89478))
> [@qlover/fe-release Release] Branch:master, Tag:0.1.4, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 0.1.6
* support release plugin ([#266](https://github.com/qlover/fe-base/issues/266)) ([23fba14](https://github.com/qlover/fe-base/commit/23fba1455919f794e5609ddab03cfb99c40ad3b8))
> [@qlover/fe-release Release] Branch:master, Tag:0.1.6, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.1.4
* remove first error default break chain ([#279](https://github.com/qlover/fe-base/issues/279)) ([bdabf8a](https://github.com/qlover/fe-base/commit/bdabf8aa1bdf37fc9121ca75a4a5924d52b21af0))
> [@qlover/fe-utils Release] Branch:master, Tag:1.1.4, Env:production

- packages/scripts-context/CHANGELOG.md
- packages/scripts-context/package.json
- 🏷️ Version: 0.0.7
* fe-release branchName arg, and change default branchName tpl:release-${pkgName}-${tagName} ([#291](https://github.com/qlover/fe-base/issues/291)) ([e89652c](https://github.com/qlover/fe-base/commit/e89652c499b8e20753b602eeb49865b303615e12))
> [@qlover/scripts-context Release] Branch:master, Tag:0.0.7, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 0.1.7
* fe-release branchName arg, and change default branchName tpl:release-${pkgName}-${tagName} ([#291](https://github.com/qlover/fe-base/issues/291)) ([e89652c](https://github.com/qlover/fe-base/commit/e89652c499b8e20753b602eeb49865b303615e12))
> [@qlover/fe-release Release] Branch:master, Tag:0.1.7, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 1.0.9
* no workspace tagname ([#333](https://github.com/qlover/fe-base/issues/333)) ([595fefe](https://github.com/qlover/fe-base/commit/595fefe4e1bce4f97ade1899a5691af39c55e67d))
> [release-@qlover/fe-release-1.0.9 Release] Branch:master, Tag:1.0.9, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/__tests__/utils/loader.test.ts
- packages/fe-release/package.json
- 🏷️ Version: 2.0.4
* **release:** change skip-changeset arg ([#340](https://github.com/qlover/fe-base/issues/340)) ([fffc35a](https://github.com/qlover/fe-base/commit/fffc35a52e768cf2739564e748d8abadab5dc3db))
> [release-@qlover/fe-release-2.0.4 Release] Branch:master, Tag:2.0.4, Env:production

- packages/env-loader/CHANGELOG.md
- packages/env-loader/package.json
- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: @qlover/env-loader@0.1.1 @qlover/fe-release@2.0.12
- Enable bumping versions with workspace protocol only in changeset configuration (#360)
----------------------
- Enhance Changelog plugin to include '--update-dependencies' option in changesets CLI command for improved dependency management during versioning. (#360)
- Enable bumping versions with workspace protocol only in changeset configuration (#360)
- Enhance Changelog plugin to include '--update-dependencies' option in changesets CLI command for improved dependency management during versioning. (#360)
- add dry run script for release PRs and update changelog template formatting (#358)
- enhance commit flattening logic and improve tag existence check; clean up Changelog …
> [batch-1745716924960-@qlover/env-loader@0.1.1_@qlover/fe-release@2.0.12-2-packages Release] Branch:master, Tag:batch-2-2025-04-27, Env:production

- packages/env-loader/__tests__/Env.test.ts
- packages/env-loader/package.json
- packages/env-loader/src/Env.ts
- pnpm-lock.yaml
- Updated dependencies in package.json and pnpm-lock.yaml to use @qlover/logger instead of @qlover/fe-corekit.
- Changed type references from Logger to LoggerInterface in Env.ts and Env.test.ts for improved type safety.
- Adjusted logger handling in the Env class to align with the new logger interface.
> refactor(env-loader): replace @qlover/fe-corekit with @qlover/logger

- packages/fe-corekit/CHANGELOG.md
- packages/fe-corekit/package.json
- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: @qlover/fe-release@2.1.5
- add option to ignore non-updated packages and enhance workspace handling (#385)
- Introduced `--changelog.ignore-non-updated-packages` CLI option to allow skipping non-updated packages in changelog generation.
- Updated `ChangelogProps` to include `ignoreNonUpdatedPackages` configuration.
- Enhanced `WorkspacesProps` to manage `changedPaths` and `packages` more effectively.
- Implemented `restoreIgnorePackages` method to restore non-changed packages during the changelog process.
- Adjusted package manager fallback from `npm` to `npx` for executing changeset commands.
----------------------
> [release-@qlover/fe-release@2.1.5] Branch:master, Tag:@qloveer/fe-release@2.1.5, Env:production

- fe-config.json
- packages/fe-release/__tests__/implements/changelog/GitChangelog.test.ts
- packages/fe-release/__tests__/implements/changelog/GitChangelogFormatter.test.ts
- packages/fe-release/src/implments/changelog/GitChangeLog.ts
- packages/fe-release/src/implments/changelog/GitChangelogFormatter.ts
- packages/fe-release/src/interface/ChangeLog.ts
- Updated GitChangelog to parse and include commit body along with the title.
- Enhanced GitChangelogFormatter to conditionally format and display commit body in the changelog.
- Introduced commitBody option in GitChangelogOptions to control the inclusion of commit body in the output.
- Updated related interfaces to accommodate the new body field in commitlint.
> feat(changelog): add support for commit body in changelog generation

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 2.3.0
- **changelog:** add support for commit body in changelog generation ([5383055](https://github.com/qlover/fe-base/commit/5383055d2abb095df40575ce2d40e4c40827e422)) ([#398](https://github.com/qlover/fe-base/pull/398))
- Updated GitChangelog to parse and include commit body along with the title.
- Enhanced GitChangelogFormatter to conditionally format and display commit body in the changelog.
- Introduced commitBody option in GitChangelogOptions to control the inclusion of commit body in the output.
- Updated related interfaces to accommodate the new body field in commitlint.
Co-authored-by: QRJ <renjie.qin@brain.im>
> [release-@qlover/fe-release-2.3.0 Release] Branch:master, Tag:2.3.0, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 2.3.1
- **changelog:** conditionally execute git restore for unchanged packages ([b419a2a](https://github.com/qlover/fe-base/commit/b419a2a42d810c89a6d5c04be61fc100724f43ad)) ([#403](https://github.com/qlover/fe-base/pull/403))
- Added a check to ensure that the git restore command is only executed if there are packages that have not changed, improving the efficiency of the Changelog plugin.
> [release-@qlover/fe-release-2.3.1 Release] Branch:master, Tag:2.3.1, Env:production

- packages/fe-release/__tests__/utils/pather.test.ts
- packages/fe-release/src/plugins/Changelog.ts
- packages/fe-release/src/plugins/githubPR/GithubChangelog.ts
- packages/fe-release/src/plugins/githubPR/GithubManager.ts
- packages/fe-release/src/utils/pather.ts
- Introduced the Pather class for reliable path normalization and comparison across Windows and POSIX systems, providing methods like `toLocalPath`, `isSubPath`, `startsWith`, and `containsPath`.
- Added extensive unit tests for the Pather class to ensure functionality and edge case handling.
- Updated Changelog and GithubChangelog plugins to utilize the new Pather utility for improved path handling in commit filtering.
These enhancements improve path management capabilities within the project, ensuring consistent behavior across different operating systems.
> feat(pather): add cross-platform path utility and comprehensive tests

- packages/corekit-bridge/__tests__/request-plugins/RequestCommonPlugin.test.ts
- packages/corekit-bridge/src/core/request-plugins/RequestCommonPlugin.ts
- Introduced comprehensive unit tests for the RequestCommonPlugin, covering initialization, token handling, header management, request data merging, and response processing.
- Enhanced test coverage for various scenarios, including edge cases and integration flows, ensuring robust functionality and reliability of the plugin.
These additions improve the overall test suite for the corekit-bridge, facilitating better maintenance and confidence in the plugin's behavior.
> feat(corekit-bridge): add unit tests for RequestCommonPlugin

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.1.1
- **corekit-bridge:** add unit tests for RequestCommonPlugin ([7703647](https://github.com/qlover/fe-base/commit/7703647730153726bbc190132dc2fb4167a46fea)) ([#447](https://github.com/qlover/fe-base/pull/447))
- Introduced comprehensive unit tests for the RequestCommonPlugin, covering initialization, token handling, header management, request data merging, and response processing.
- Enhanced test coverage for various scenarios, including edge cases and integration flows, ensuring robust functionality and reliability of the plugin.
These additions improve the overall test suite for the corekit-bridge, facilitating better maintenance and confidence in the plugin's behavior.
> This PR is auto created by release process, please …
> [release-@qlover/corekit-bridge-1.1.1 Release] Branch:master, Tag:1.1.1, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.1.2
- **corekit-bridge:** refactor user authentication interfaces and enhance token management ([12770ce](https://github.com/qlover/fe-base/commit/12770cec8eee16740823dee0deead528aea1ec3a)) ([#449](https://github.com/qlover/fe-base/pull/449))
- Updated UserAuthService to use `api` instead of `service` for improved clarity in the authentication flow.
- Introduced `setUserAuthStore` method in UserAuthApiInterface to manage user authentication storage.
- Enhanced UserAuthStore with methods to set and get user tokens, improving token management capabilities.
- Made storage options in UserToken interface optional, allowing for more flexible configurations.
- Added comprehensive unit tests to validate the new implementations and …
> [release-@qlover/corekit-bridge-1.1.2 Release] Branch:master, Tag:1.1.2, Env:production

- packages/create-app/templates/react-app/config/app.router.ts
- packages/create-app/templates/react-app/config/common.ts
- packages/create-app/templates/react-app/src/base/services/I18nService.ts
- packages/create-app/templates/react-app/src/base/services/RouteService.ts
- packages/create-app/templates/react-app/src/core/registers/RegisterCommon.ts
- packages/create-app/templates/react-app/src/pages/404.tsx
- packages/create-app/templates/react-app/src/pages/500.tsx
- packages/create-app/templates/react-app/src/pages/base/RedirectPathname.tsx
- packages/create-app/templates/react-app/src/uikit/components/LocaleLink.tsx
- packages/create-app/templates/react-app/src/uikit/hooks/useI18nGuard.ts
- Added support for locale-based routing in the application, allowing routes to include language prefixes.
- Introduced `baseNoLocaleRoutes` to manage routes without localization, improving flexibility in route handling.
- Updated `I18nService` to conditionally cache user language based on locale routing settings.
- Enhanced `RouteService` to handle locale routes and added methods for redirection and language validation.
- Modified `RegisterCommon` to utilize the appropriate route configuration based on locale settings.
- Updated various components and hooks to integrate with the new routing logic, ensuring seamless navigation and language handling.
These changes aim to improve the user experience by providing localized routes and better language management.
> feat(router): implement locale routing and enhance route configuration

- packages/scripts-context/CHANGELOG.md
- packages/scripts-context/package.json
- 🏷️ Version: 1.1.3
- **ScriptContext:** streamline environment option retrieval in getDefaultOptions method ([6fe72ec](https://github.com/qlover/fe-base/commit/6fe72ecf2d4d0414fa3c2b07549f4e6c4b6d91e2)) ([#495](https://github.com/qlover/fe-base/pull/495))
- Updated the getDefaultOptions method to simplify the logic for retrieving the environment variable. The environment is now set directly from this.options.env or fetched using Env.searchEnv if not provided, improving code clarity and maintainability.
> [release-@qlover/scripts-context-1.1.3 Release] Branch:master, Tag:1.1.3, Env:production

- packages/create-app/src/cli.ts
- packages/create-app/src/index.mts
- packages/create-app/src/index.ts
- packages/create-app/tsup.config.ts
- Changed the entry point in tsup.config.ts from 'src/index.ts' to 'src/index.mts' for better module support.
- Introduced a new CLI interface in src/cli.ts to handle command-line arguments and application logic.
- Created a new entry file src/index.mts that imports and executes the main function from the CLI, enhancing modularity and clarity.
- Removed the old main function from src/index.ts, streamlining the codebase and improving maintainability.
These changes aim to improve the application's structure and facilitate better command-line interactions.
> refactor(create-app): structure and update entry points
