- .gitattributes
change .gitattributes file format
> fix(.gitattributes): change file format

- .env
- .env.template
- .github/workflows/build.yml
- .github/workflows/release.yml
- .gitignore
- .npmrc
- .release-it.json
- package.json
- scripts/bin/release.js
- scripts/loadEnv.js
> Feat cicd build release

- .github/workflows/release.yml
- CHANGELOG.md
- package.json
- scripts/bin/release.js
> Revert "build: change build name"

- .github/workflows/release.yml
- package.json
> Test master ci

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.65
> Release test-release-gh v1.0.65

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.71
> [From bot] Release main v1.0.71

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.81
> [From bot] Release master v1.0.81

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.89
> [From bot] Release master v1.0.89

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.93
> [From bot] Release master v1.0.93

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.94
> [From bot] Release master v1.0.94

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.95
> [From bot] Release master v1.0.95

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.97
> [From bot] Release master v1.0.97

- .release-it.json
- scripts/bin/release.js
This PR includes version bump to v1.0.95
> [From bot] Release master v1.0.95 from development

- scripts/bin/release.js
- scripts/utils/runCommand.js
This PR includes version bump to v1.0.97
> [From bot] Release master v1.0.97 from development

- .github/workflows/build.yml
- .github/workflows/release.yml
- scripts/bin/release.js
- scripts/package.json
- scripts/utils/runCommand.js
This PR includes version bump to v1.0.98
> [From bot] Release master v1.0.98 from development

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.99
> [From bot] Release master v1.0.99 from production

- .github/workflows/release.yml
> Revert "fix: pr-branch var name in release"

- .release-it.json
- CHANGELOG.md
- package.json
- scripts/lib/relesae.js
- scripts/lib/shell.js
This PR includes version bump to v1.0.102
> [From bot] Release test v1.0.102 from development

- package.json
> build: upgrade version

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.106
> [From bot] Release master v1.0.106 from production

- .env
- .github/workflows/build.yml
- .github/workflows/release.yml
- config/app.config.cjs
- package.json
- packages/main/index.ts
- tsup.config.ts
This PR includes version bump to v1.0.106
> [From bot] Release build/tsup v1.0.106 from development

- .env
- .github/workflows/build.yml
- .github/workflows/release.yml
- config/app.config.cjs
- package.json
- packages/main/index.ts
- tsup.config.ts
> feat: build use tsup

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.107
> [From bot] Release master v1.0.107 from production

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.108
> [From bot] Release master v1.0.108 from production

- .github/workflows/release.yml
- package.json
> Revert "build: add quick script name"

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.109
> [From bot] Release master v1.0.109 from production

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.110
> [From bot] Release master v1.0.110 from production

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.111
> [From bot] Release master v1.0.111 from production

- CHANGELOG.md
- package.json
This PR includes version bump to v1.0.112
> [From bot] Release master v1.0.112 from production

- CHANGELOG.md
- package.json
This PR includes version bump to 1.0.112
> [Bot Release] Branch:master, Tag:1.0.112, Env:production

- .eslintrc.cjs
- jest.config.cjs
- package.json
- packages/fe-utils/README.md
- packages/fe-utils/__tests__/encrypt.test.ts
- packages/fe-utils/__tests__/executor.test.ts
- packages/fe-utils/__tests__/logger.test.ts
- packages/fe-utils/common/executor/index.ts
- packages/fe-utils/common/index.ts
- packages/fe-utils/common/logger/index.ts
- packages/fe-utils/package.json
- packages/fe-utils/rollup.config.js
- packages/fe-utils/server/encrypt/Encryptor.ts
- packages/fe-utils/server/encrypt/StringEntrypt.ts
- packages/fe-utils/server/encrypt/StringZlibEncrypt.ts
- packages/fe-utils/server/encrypt/index.ts
- packages/fe-utils/server/index.ts
- packages/fe-utils/tests/encrypt.test.ts
- packages/fe-utils/tests/executor.test.ts
- packages/fe-utils/tests/logger.test.ts
- packages/fe-utils/tsconfig.json
- packages/fe-utils/type.d.ts
- packages/fe-utils/vitest.config.ts
- scripts/prebuild.js
- tsconfig.json
- tsconfig.test.json
> feat: base fe-utils

- .github/workflows/general-check.yml
> test: add pkg:scripts label

- packages/fe-scripts/bin/create-release-pr.js
- packages/fe-scripts/bin/release.js
- packages/fe-scripts/index.d.ts
- packages/fe-scripts/lib/Release.js
> Revert "build: fe-scripts test 0.3.4 CI"

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [Fe-Scripts Release] Branch:master, Tag:0.3.5, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.3.6
* remove auto merge ([#121](https://github.com/qlover/fe-base/issues/121)) ([434b198](https://github.com/qlover/fe-base/commit/434b198e174963c2f683362c22cc5295173a7a63))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.3.6, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.3.7
* remove auto merge ([#121](https://github.com/qlover/fe-base/issues/121)) ([434b198](https://github.com/qlover/fe-base/commit/434b198e174963c2f683362c22cc5295173a7a63))
* release push changlog.md ([#123](https://github.com/qlover/fe-base/issues/123)) ([1952ae1](https://github.com/qlover/fe-base/commit/1952ae1caad2a965ec233eca18092bb0b356987b))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.3.7, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.4
* **.env:** use dotenv load .env ([3879596](https://github.com/qlover/fe-base/commit/3879596f6ca4017b1f12e4fc3ea5c928dc575fd0))
* add packages/work ([18f528e](https://github.com/qlover/fe-base/commit/18f528e9d41ca43abe615b57863c8acde96952ca))
* add request exec ([#118](https://github.com/qlover/fe-base/issues/118)) ([7e4783b](https://github.com/qlover/fe-base/commit/7e4783b250dc585cb030ced9849ba093a56d7aec))
* **ci.yml:** add ci ([df24b88](https://github.com/qlover/fe-base/commit/df24b883138c710a3f1b8d2f97acf415d5e3c5e7))
* clean branch ([075952b](https://github.com/qlover/fe-base/commit/075952b5230a4518a7243c9d716e3a245eac1115))
* clean branch ([b5156ce](https://github.com/qlover/fe-base/commit/b5156ceebb5caa3266147a0255ee …
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.4, Env:production

- package.json
- packages/fe-scripts/package.json
> fix: fe scripts commitizen not found

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.3.9
* comm commitizen ([#128](https://github.com/qlover/fe-base/issues/128)) ([042ff3a](https://github.com/qlover/fe-base/commit/042ff3a71ab6bec039ee4fa1bc3f4fc116f9dd35))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.3.9, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.7, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [@qlover/fe-scripts Release] Branch:master, Tag:0.3.10, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.10, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.11
* Serializer JSON and Base64 ([#144](https://github.com/qlover/fe-base/issues/144)) ([9fcfa1a](https://github.com/qlover/fe-base/pull/144/commits/9fcfa1adc336a75851b5d057540262af7514b2a3))
* new fe-utils docs ([#144](https://github.com/qlover/fe-base/issues/144)) ([2636773](https://github.com/qlover/fe-base/pull/144/commits/263677347edcffb44651d6663fdda53d39e109d9))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.11, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.12
* code2markdown table decription ([#146](https://github.com/qlover/fe-base/issues/146)) ([39db11e](https://github.com/qlover/fe-base/commit/39db11e56f225a4364398f090db299840f6a2ac5))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.12, Env:production

- packages/fe-scripts/scripts/release.js
github release not auto published
> fix(fe-scripts/scripts/release.js): not clear github_token var

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.4.0
* fe scripts context ([#150](https://github.com/qlover/fe-base/issues/150)) ([64ef1a0](https://github.com/qlover/fe-base/commit/64ef1a05b170deefd3f7dc03625a03510ae2599e))
* **fe-scripts/scripts/release.js:** not clear github_token var ([#148](https://github.com/qlover/fe-base/issues/148)) ([1538ae1](https://github.com/qlover/fe-base/commit/1538ae15c1af038702897b47ce01a148dbf0e8d4))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.4.0, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.13
* fe-scripts type ([#153](https://github.com/qlover/fe-base/issues/153)) ([99da575](https://github.com/qlover/fe-base/commit/99da575a75eb13cdbc2e7546e13a851cb1329abc))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.13, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.4.1
* fe-scripts type ([#153](https://github.com/qlover/fe-base/issues/153)) ([99da575](https://github.com/qlover/fe-base/commit/99da575a75eb13cdbc2e7546e13a851cb1329abc))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.4.1, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.4.2
* clean branch command options ([#158](https://github.com/qlover/fe-base/issues/158)) ([387e3c7](https://github.com/qlover/fe-base/commit/387e3c7aba1303b4caaef0053683d9e67ba981fa))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.4.2, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.14, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.15
* update fe-utils ([#162](https://github.com/qlover/fe-base/issues/162)) ([10c7144](https://github.com/qlover/fe-base/commit/10c71442672066e243591ab1d0fd923ef97dd2a6))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.15, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [@qlover/fe-scripts Release] Branch:master, Tag:0.4.3, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.16, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/__tests__/request/RequestScheduler.network.test.ts
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.17
* Storage interface, and JSONStorage ([#167](https://github.com/qlover/fe-base/issues/167)) ([7313aad](https://github.com/qlover/fe-base/commit/7313aad85682e6f5f3429e7a86f2c44f702abc5e))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.17, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.18, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.0.19
* fe utils interface ([#172](https://github.com/qlover/fe-base/issues/172)) ([ad32dd8](https://github.com/qlover/fe-base/commit/ad32dd815d80cf839103ae08ee5174ad73522624))
* eslint config ([#171](https://github.com/qlover/fe-base/issues/171)) ([fc14f4b](https://github.com/qlover/fe-base/commit/fc14f4b2fb3196394d3b470eaa25bcfb428c7861))
* test file use browser globals ([#173](https://github.com/qlover/fe-base/issues/173)) ([acaa0a4](https://github.com/qlover/fe-base/commit/acaa0a4417ee0c4f40982fe7c995744be3338a23))
> [@qlover/fe-utils Release] Branch:master, Tag:1.0.19, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.4.4
* fe utils interface ([#172](https://github.com/qlover/fe-base/issues/172)) ([ad32dd8](https://github.com/qlover/fe-base/commit/ad32dd815d80cf839103ae08ee5174ad73522624))
* eslint config ([#171](https://github.com/qlover/fe-base/issues/171)) ([fc14f4b](https://github.com/qlover/fe-base/commit/fc14f4b2fb3196394d3b470eaa25bcfb428c7861))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.4.4, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.5.1
* fe code2md use typescript ([#180](https://github.com/qlover/fe-base/issues/180)) ([5f086b1](https://github.com/qlover/fe-base/commit/5f086b11fbe98aa410996ce95f8c0b5b5f06b6e5))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.5.1, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.1.1
* fe code2md use typescript ([#180](https://github.com/qlover/fe-base/issues/180)) ([5f086b1](https://github.com/qlover/fe-base/commit/5f086b11fbe98aa410996ce95f8c0b5b5f06b6e5))
> [@qlover/fe-utils Release] Branch:master, Tag:1.1.1, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
- 🏷️ Version: 1.1.2
* Template fe react ([#183](https://github.com/qlover/fe-base/issues/183)) ([d044a49](https://github.com/qlover/fe-base/commit/d044a49917f647179eb4d8c391a13a785627e02c))
> [@qlover/fe-utils Release] Branch:master, Tag:1.1.2, Env:production

- packages/fe-utils/CHANGELOG.md
- packages/fe-utils/package.json
> [@qlover/fe-utils Release] Branch:master, Tag:1.1.3, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.5.2
* check packages release ci scripts ([#198](https://github.com/qlover/fe-base/issues/198)) ([ea49c84](https://github.com/qlover/fe-base/commit/ea49c847a05875d693876c0e4c35547c891117a2))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.5.2, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [@qlover/fe-scripts Release] Branch:master, Tag:0.5.3, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.0.4
* .gitignore no file ([#207](https://github.com/qlover/fe-base/issues/207)) ([e61d468](https://github.com/qlover/fe-base/commit/e61d4683a072048326205272d927e7e67b87ba70))
> [@qlover/create-app Release] Branch:master, Tag:0.0.4, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.1
* create app v0.1 ([#209](https://github.com/qlover/fe-base/issues/209)) ([b730d76](https://github.com/qlover/fe-base/commit/b730d76512a9e1ce765ec77145abfe179b585178))
> [@qlover/create-app Release] Branch:master, Tag:0.1.1, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.2
* add script-context ([#213](https://github.com/qlover/fe-base/issues/213)) ([e021441](https://github.com/qlover/fe-base/commit/e021441180d4c4bd89947b155d39224f89699fda))
> [@qlover/create-app Release] Branch:master, Tag:0.1.2, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.3, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.4, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [@qlover/fe-scripts Release] Branch:master, Tag:0.7.2, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.9.2
* fe-release publish path check ([#236](https://github.com/qlover/fe-base/issues/236)) ([364984e](https://github.com/qlover/fe-base/commit/364984e3b3c27ed3a1e5cd3cc12d3c1184916fab))
> [@qlover/fe-scripts Release] Branch:master, Tag:0.9.2, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.5, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.6
* template context ([#241](https://github.com/qlover/fe-base/issues/241)) ([9fb3046](https://github.com/qlover/fe-base/commit/9fb3046e3e67c02e5fe4fea81a9a3ef8422e3013))
> [@qlover/create-app Release] Branch:master, Tag:0.1.6, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.7
* optz create-app deep ([#244](https://github.com/qlover/fe-base/issues/244)) ([c0a89ef](https://github.com/qlover/fe-base/commit/c0a89ef5dc2f3cc216b4fc1968b1b626c58947d5))
> [@qlover/create-app Release] Branch:master, Tag:0.1.7, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.8, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.9
* add pnpm install ([#248](https://github.com/qlover/fe-base/issues/248)) ([e1e9f48](https://github.com/qlover/fe-base/commit/e1e9f4841365c51e9b8ea7b01ac6fc70e35eec37))
> [@qlover/create-app Release] Branch:master, Tag:0.1.9, Env:production

- packages/create-app/configs/_common/.github/workflows/release.yml.template
- packages/fe-release/src/plugins/CreateReleasePullRequest.ts
- packages/fe-scripts/bin/commit.js
- packages/fe-scripts/src/scripts/commit.ts
1. Error cz and changlog module not found when running release scripts with pnpm
2. Not allow workflow permissions relesae scripts not working
3. create-app pack-app yml no install dependencies
> Fix commit scripts cz module

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
> [@qlover/fe-scripts Release] Branch:master, Tag:0.10.1, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.10, Env:production

- packages/scripts-context/CHANGELOG.md
- packages/scripts-context/package.json
- 🏷️ Version: 0.0.5
* remove shelljs dep, add dep inject ([#260](https://github.com/qlover/fe-base/issues/260)) ([c38112f](https://github.com/qlover/fe-base/commit/c38112f4540d6bd5dd89c419c6ecfa11f195dcbd))
> [@qlover/scripts-context Release] Branch:master, Tag:0.0.5, Env:production

- packages/scripts-context/CHANGELOG.md
- packages/scripts-context/package.json
- 🏷️ Version: 0.0.6
* **execPromise:** throw an Error ([#263](https://github.com/qlover/fe-base/issues/263)) ([816c9f9](https://github.com/qlover/fe-base/commit/816c9f9e442e8b6e7fa05feb9977d8a31bbfc677))
> [@qlover/scripts-context Release] Branch:master, Tag:0.0.6, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
> [@qlover/create-app Release] Branch:master, Tag:0.1.11, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.12
* add inversify ioc ([#270](https://github.com/qlover/fe-base/issues/270)) ([8c7ba06](https://github.com/qlover/fe-base/commit/8c7ba06bc5bef63d85c59a94737afac9be59138f))
> [@qlover/create-app Release] Branch:master, Tag:0.1.12, Env:production

- packages/create-app/templates/react-app/lib/api-client/interface/ApiClient.ts
- packages/create-app/templates/react-app/lib/request-common-plugin/index.ts
- packages/create-app/templates/react-app/src/base/apis/feApi/FeApi.ts
- packages/create-app/templates/react-app/src/base/apis/feApi/FeApiTransaction.ts
- packages/create-app/templates/react-app/src/base/apis/userApi/UserApi.ts
- packages/create-app/templates/react-app/src/base/apis/userApi/UserApiTransaction.ts
- packages/create-app/templates/react-app/src/base/apis/userApi/UserApiType.ts
- packages/create-app/templates/react-app/src/base/cases/RequestStatusCatcher.ts
- packages/create-app/templates/react-app/src/base/cases/apisPlugins/ApiCatchPlugin.ts
- packages/create-app/templates/react-app/src/base/cases/apisPlugins/ApiMockPlugin.ts
- packages/create-app/templates/react-app/src/base/cases/apisPlugins/ApiPickDataPlugin.ts
- packages/create-app/templates/react-app/src/base/port/RequestCatcherInterface.ts
- packages/create-app/templates/react-app/src/core/bootstraps/BootstrapApp.ts
- packages/create-app/templates/react-app/src/uikit/controllers/RequestController.ts
- packages/create-app/templates/react-app/src/uikit/controllers/UserController.ts
1. fix request common plugin assign data error
> fix: RequestCommonPlugin assign data key error

- packages/fe-corekit/CHANGELOG.md
- packages/fe-corekit/package.json
- 🏷️ Version: 1.2.1
* fe corekit and remove fe utils ([#281](https://github.com/qlover/fe-base/issues/281)) ([e333c7f](https://github.com/qlover/fe-base/commit/e333c7fe0518cb5ec34ecc7423dffb511f835324))
> [@qlover/fe-corekit Release] Branch:master, Tag:1.2.1, Env:production

- packages/fe-corekit/CHANGELOG.md
- packages/fe-corekit/package.json
- 🏷️ Version: 1.2.2
* request manager ([#284](https://github.com/qlover/fe-base/issues/284)) ([2351827](https://github.com/qlover/fe-base/pull/284/commits/2351827e1def9c8d9c62783d974b674dd8ad256e))
* request transaction ([#284](https://github.com/qlover/fe-base/issues/284)) ([f7fea1](https://github.com/qlover/fe-base/pull/284/commits/f7fea15db5ca3c5df5f9351aca807510626a396c))
> [@qlover/fe-corekit Release] Branch:master, Tag:1.2.2, Env:production

- packages/create-app/templates/react-app/config/feapi.mock.json
- packages/create-app/templates/react-app/src/base/apis/AiApi.ts
- packages/create-app/templates/react-app/src/base/apis/feApi/FeApiType.ts
- packages/create-app/templates/react-app/src/base/apis/userApi/UserApi.ts
- packages/create-app/templates/react-app/src/base/apis/userApi/UserApiType.ts
- packages/create-app/templates/react-app/src/base/cases/apisPlugins/ApiCatchPlugin.ts
- packages/create-app/templates/react-app/src/core/AppConfig.ts
- packages/create-app/templates/react-app/src/core/bootstraps/index.ts
- packages/create-app/templates/react-app/src/core/registers/RegisterControllers.ts
- packages/create-app/templates/react-app/src/pages/base/Request.tsx
- packages/create-app/templates/react-app/src/uikit/controllers/RequestController.ts
- packages/create-app/templates/react-app/src/uikit/utils/RequestLogger.ts
1. add functional API implemention(AiAPI)
> Feat api simple

- packages/fe-release/bin/release.js
- packages/fe-release/src/plugins/CreateReleasePullRequest/BranchManager.ts
- packages/scripts-context/src/feConfig.ts
1. fe-release add -b(--branchName) arg
2. scripts-context change default releaese branchName: release-${pkgName}-${tagName}
> feat: fe-release branchName arg, and change default branchName tpl:release-${pkgName}-${tagName}

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 0.0.1
* corekit-bridge ([#294](https://github.com/qlover/fe-base/issues/294)) ([e5e2237](https://github.com/qlover/fe-base/commit/e5e2237f8f5cd2294fd4667e08a1714999c52fa1))
> [@qlover/corekit-bridge Release] Branch:master, Tag:0.0.1, Env:production

- packages/fe-release/src/Plugin.ts
- packages/fe-release/src/cli.ts
- packages/fe-release/src/defaults.ts
- packages/fe-release/src/index.ts
- packages/fe-release/src/interface/ReleaseContext.ts
- packages/fe-release/src/plugins/CheckEnvironment.ts
- packages/fe-release/src/plugins/CreateReleasePullRequest/BranchManager.ts
- packages/fe-release/src/plugins/CreateReleasePullRequest/ChangelogManager.ts
- packages/fe-release/src/plugins/CreateReleasePullRequest/PullRequestManager.ts
- packages/fe-release/src/plugins/CreateReleasePullRequest/ReleaseBase.ts
- packages/fe-release/src/plugins/CreateReleasePullRequest/index.ts
- packages/fe-release/src/plugins/PublishNpm.ts
- packages/fe-release/src/plugins/PublishPath.ts
- packages/fe-release/src/release.ts
- packages/fe-release/src/type.ts
- packages/fe-release/src/util.ts
1. add namespace(pluginName) config to context.options
> feat: add config namesapce

- packages/scripts-context/CHANGELOG.md
- packages/scripts-context/package.json
- 🏷️ Version: 0.0.8
* add cache controller ([#310](https://github.com/qlover/fe-base/issues/310)) ([2a76aea](https://github.com/qlover/fe-base/commit/2a76aeaa53f0d681c637b48febfe62979a1e7496))
> [@qlover/scripts-context Release] Branch:master, Tag:0.0.8, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 1.0.8
* use changset publish/release ([#329](https://github.com/qlover/fe-base/issues/329)) ([#330](https://github.com/qlover/fe-base/issues/330)) ([8ef77ba](https://github.com/qlover/fe-base/commit/8ef77ba7f0ecf4eb2fa4b52d92ee89aa27b4285a))
> [release-@qlover/fe-release-1.0.8 Release] Branch:master, Tag:1.0.8, Env:production

- packages/fe-release/__tests__/utils/loader.test.ts
- packages/fe-release/package.json
- Updated package version from 2.0.0 to 2.0.1 in package.json.
- Improved module resolution logic in loader tests to handle additional cases for 'file://' paths.
> chore: enhance module resolution in tests

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
> [release-@qlover/fe-release-2.0.2 Release] Branch:master, Tag:2.0.2, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.1.16
* .gitignore no file ([#207](https://github.com/qlover/fe-base/issues/207)) ([e61d468](https://github.com/qlover/fe-base/commit/e61d4683a072048326205272d927e7e67b87ba70))
* add pnpm install ([#248](https://github.com/qlover/fe-base/issues/248)) ([e1e9f48](https://github.com/qlover/fe-base/commit/e1e9f4841365c51e9b8ea7b01ac6fc70e35eec37))
* release publish npm ([#327](https://github.com/qlover/fe-base/issues/327)) ([fa26d04](https://github.com/qlover/fe-base/commit/fa26d04eab2fa1ea4baa05c4d3502e5a873d5c8c))
* add inversify ioc ([#270](https://github.com/qlover/fe-base/issues/270)) ([8c7ba06](https://github.com/qlover/fe-base/commit/8c7ba06bc5bef63d85c59a94737afac9be59138f))
* add script-context …
> [release-@qlover/create-app-0.1.16 Release] Branch:master, Tag:0.1.16, Env:production

- .changeset/config.json
- packages/env-loader/package.json
- packages/fe-release/src/plugins/Changelog.ts
see: https://github.com/changesets/changesets/issues/568
- If separate version and publish suggest adding bumpVersionsWithWorkspaceProtocolOnly:true 
- if not suggest removing
> Fix no update dependencies

- packages/logger/CHANGELOG.md
- packages/logger/package.json
- pnpm-lock.yaml
- 🏷️ Version: 0.0.1
- add @qlover/logger package with ConsoleAppender and TimestampFormatter (#369)
- Introduced a new logging package, @qlover/logger, which includes a Logger class for structured logging.
- Implemented ConsoleAppender for console output and TimestampFormatter for formatted timestamps.
- Added comprehensive tests for Logger, ConsoleAppender, and TimestampFormatter to ensure functionality.
- Created CHANGELOG.md and README.md for the new package.
- enhance @qlover/logger package with new build script and documentation updates (#369)
- Added a new build script for the logger package to streamline the build process.
- Introduced an English README file for better accessibility and understanding of the logger's features and usage. …
> [release-@qlover/logger-0.0.1 Release] Branch:master, Tag:0.0.1, Env:production

- packages/fe-scripts/CHANGELOG.md
- packages/fe-scripts/package.json
- 🏷️ Version: 0.11.4
- update build script to include rebuild step (#377)
- Modified the build script in package.json to append a rebuild command, ensuring that dependencies are rebuilt after the main build process.
----------------------
- migrate build system from Rollup to tsup (#377)
- Updated package.json to change entry points and output directories for the new build system.
- Removed Rollup configuration file and replaced it with tsup configuration for better performance and simplicity.
- Added new CLI scripts for various functionalities, including check-packages, clean-branch, clean, commit, and setup-husky.
- Adjusted TypeScript configuration to disable source maps for production builds.
- Removed deprecated files and dependencies …
> [release-@qlover/fe-scripts-0.11.4 Release] Branch:master, Tag:0.11.4, Env:production

- fe-config.json
- packages/corekit-interface/CHANGELOG.md
- packages/corekit-interface/README.md
- packages/corekit-interface/README_EN.md
- packages/corekit-interface/__tests__/executor/Executor.test.ts
- packages/corekit-interface/__tests__/executor/ExecutorError.test.ts
- packages/corekit-interface/package.json
- packages/corekit-interface/src/encrypt/Encryptor.ts
- packages/corekit-interface/src/encrypt/index.ts
- packages/corekit-interface/src/executor/Executor.ts
- packages/corekit-interface/src/executor/ExecutorContext.ts
- packages/corekit-interface/src/executor/ExecutorError.ts
- packages/corekit-interface/src/executor/ExecutorPlugin.ts
- packages/corekit-interface/src/executor/index.ts
- packages/corekit-interface/src/index.ts
- packages/corekit-interface/src/request/RequestAdapter.ts
- packages/corekit-interface/src/request/RequestError.ts
- packages/corekit-interface/src/request/RequestTransactionInterface.ts
- packages/corekit-interface/src/request/index.ts
- packages/corekit-interface/src/serializer/Serializer.ts
- packages/corekit-interface/src/serializer/index.ts
- packages/corekit-interface/src/storage/Storage.ts
- packages/corekit-interface/src/storage/index.ts
- packages/corekit-interface/tsconfig.json
- packages/corekit-interface/tsup.config.ts
- Added corekit interface package with essential files including README, CHANGELOG, and package.json.
- Implemented core functionalities for encryption, executor, request, serialization, and storage with type definitions.
- Set up tsup for building the package and included test files for executor functionalities.
> feat(corekit-interface): initialize @qlover/corekit-interface package

- packages/corekit-interface/CHANGELOG.md
- packages/corekit-interface/package.json
- pnpm-lock.yaml
- 🏷️ Version: 1.0.0
- initialize @qlover/corekit-interface package (#379)
- Added corekit interface package with essential files including README, CHANGELOG, and package.json.
- Implemented core functionalities for encryption, executor, request, serialization, and storage with type definitions.
- Set up tsup for building the package and included test files for executor functionalities.
> [release-@qlover/corekit-interface-1.0.0 Release] Branch:master, Tag:1.0.0, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- packages/corekit-bridge/src/core/color-log/ColorFormatter.ts
- 🏷️ Version: 1.0.0
- enhance build configuration and export structure (#390)
- Updated Rollup configuration to utilize createBaseRollup for streamlined builds.
- Added new TypeScript configuration files for building and ESM support.
- Modified package.json to include main and module entries for better module resolution.
- Expanded exports in core index file to include additional dependencies.
- Refactored ColorFormatter to improve method visibility and added override annotation.
- remove unnecessary console.info call from test (#389)
- update import paths and refactor logger usage in documentation (#390)
- Changed import paths in README files to remove 'build' directory references for Tailwind, Vite, and TypeScript tools.
- Refactored logger …
> [release-@qlover/corekit-bridge-1.0.0 Release] Branch:master, Tag:1.0.0, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.0.1
- restore types entry and enhance exports in package.json (#392)
----------------------
> [release-@qlover/corekit-bridge-1.0.1 Release] Branch:master, Tag:1.0.1, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.0.2
- **theme-service:** enhance theme configuration and remove unused tw-generator ([1f11c20](https://github.com/qlover/fe-base/commit/1f11c20b8fda9e4208cd568e544b264b42f1b0c0)) ([#406](https://github.com/qlover/fe-base/pull/406))
- Introduced a default theme configuration with properties for DOM attribute, default theme, target element, supported themes, storage key, initialization, and store prioritization.
- Updated ThemeService to utilize the new configuration and improved theme binding logic.
- Enhanced ThemeStateGetter to conditionally access storage based on the new prioritizeStore property.
- Removed the unused tw-generator file to streamline the theme service module.
- **theme-service:** add cacheTarget option and …
> [release-@qlover/corekit-bridge-1.0.2 Release] Branch:master, Tag:1.0.2, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.0.3
- **Bootstrap:** enhance configuration and plugin integration ([4256c19](https://github.com/qlover/fe-base/commit/4256c19a044d208d73bafcab173083b727fe0fe4)) ([#409](https://github.com/qlover/fe-base/pull/409))
- Introduced BootstrapConfig interface to streamline configuration options for IOC, environment, and global plugins.
- Refactored Bootstrap class to utilize the new configuration structure, improving clarity and maintainability.
- Updated plugin initialization logic in the initialize method to support dynamic plugin loading based on provided options.
- Enhanced InjectEnv, InjectIOC, and InjectGlobal plugins to accept configuration objects, improving flexibility and usability.
- Adjusted method signatures and return …
> [release-@qlover/corekit-bridge-1.0.3 Release] Branch:master, Tag:1.0.3, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.3.3
- **LanguageSwitcher:** add language switcher component to enhance localization ([72edba8](https://github.com/qlover/fe-base/commit/72edba8a71dabba00608fceafc355cf4bc2dfd63)) ([#411](https://github.com/qlover/fe-base/pull/411))
- Introduced a new LanguageSwitcher component that allows users to change the application language.
- Integrated the component into BaseHeader for improved accessibility.
- Utilized Ant Design's Select component for a user-friendly interface.
- Implemented language change functionality that updates the URL and i18n configuration accordingly.
- **Login:** integrate Ant Design components for enhanced user experience ([d380157](https://github.com/qlover/fe-base/commit/d380157d3360ad5b9e96d0e3edeb2639a3a …
> [release-@qlover/create-app-0.3.3 Release] Branch:master, Tag:0.3.3, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.3.5
-  enhance Vite configuration and add new dependencies for improved build performance ([e14ee42](https://github.com/qlover/fe-base/commit/e14ee428d46fc48decb99762103c25d6e6c8535e)) ([#418](https://github.com/qlover/fe-base/pull/418))
- Added `terser` for advanced minification options, including console log removal and improved compression.
- Introduced `vite-plugin-imp` to optimize Ant Design imports, reducing bundle size and improving load times.
- Updated Vite configuration to define manual chunks for better code splitting and chunk management.
Co-authored-by: QRJ <renjie.qin@brain.im>
> [release-@qlover/create-app-0.3.5 Release] Branch:master, Tag:0.3.5, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.3.8
- **create-app:** update dependencies and tsup configuration for @qlover/create-app ([4a5fa84](https://github.com/qlover/fe-base/commit/4a5fa846ae6c3df97c73df5e594c3adb4fb7cda9)) ([#424](https://github.com/qlover/fe-base/pull/424))
- Reorganized package.json to move "commander" and "ora" to dependencies from devDependencies, ensuring they are included in the production build.
- Updated tsup.config.ts to enhance build configuration by defining external modules and adjusting minification and splitting settings for improved performance.
> [release-@qlover/create-app-0.3.8 Release] Branch:master, Tag:0.3.8, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.4.0
- **create-app:** update root path resolution to use dirname for compatibility with ES modules ([d091f0b](https://github.com/qlover/fe-base/commit/d091f0bc5ed17a6d16a7bedcac5416a41cba41d2)) ([#426](https://github.com/qlover/fe-base/pull/426))
> [release-@qlover/create-app-0.4.0 Release] Branch:master, Tag:0.4.0, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.4.2
- **create-app:** enhance routing and configuration with router prefix and new services ([b32795d](https://github.com/qlover/fe-base/commit/b32795d02af4234d4708a5bdcb111bf8d2a54bd6)) ([#430](https://github.com/qlover/fe-base/pull/430))
- Introduced a router prefix in the configuration to manage asset paths and API routes more effectively.
- Updated the application to utilize the new RouteService for routing logic, replacing the previous RouterController.
- Refactored user authentication handling to use UserService, improving modularity and maintainability.
- Added PublicAssetsPath service to manage public asset paths dynamically based on the router prefix.
- Updated localization files to include additional keys and ensure …
> [release-@qlover/create-app-0.4.2 Release] Branch:master, Tag:0.4.2, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.4.3
- **create-app:** enhance environment configuration and localization support ([76e5e22](https://github.com/qlover/fe-base/commit/76e5e22e41fe23ce109c303ca3974103f8a85cf6)) ([#432](https://github.com/qlover/fe-base/pull/432))
- Updated .gitignore to include .env files and added .env.template to the repository.
- Introduced a new .env.template file for environment variable configuration in the react-app template.
- Enhanced package.json scripts for development modes: added staging and production modes.
- Updated README.md to document environment variable usage with Vite.
- Added new error identifiers for token handling in Error.ts and updated UserService to utilize these identifiers.
- Improved localization files to include …
> [release-@qlover/create-app-0.4.3 Release] Branch:master, Tag:0.4.3, Env:production

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.4.4
- **create-app:** add error identifiers and localization support for new components ([0ec3780](https://github.com/qlover/fe-base/commit/0ec3780a7972acd855e1b4d2ae866575534dc094)) ([#434](https://github.com/qlover/fe-base/pull/434))
- Introduced new error identifiers in Error.ts for handling various application states, including IOC not implemented and token absence.
- Added extensive localization keys in I18n.ts for various pages and components, enhancing user experience across different languages.
- Improved error handling and messaging consistency throughout the application.
This update enhances the application's localization capabilities and error management, providing clearer feedback to users.
- **create-app:** …
> [release-@qlover/create-app-0.4.4 Release] Branch:master, Tag:0.4.4, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
> [release-@qlover/fe-release-2.3.3 Release] Branch:master, Tag:2.3.3, Env:production

- packages/fe-release/CHANGELOG.md
- packages/fe-release/package.json
- 🏷️ Version: 2.3.4
- **pather:** add cross-platform path utility and comprehensive tests ([b87a269](https://github.com/qlover/fe-base/commit/b87a269c9215c34df3646e5511792c5c6818e736)) ([#445](https://github.com/qlover/fe-base/pull/445))
- Introduced the Pather class for reliable path normalization and comparison across Windows and POSIX systems, providing methods like `toLocalPath`, `isSubPath`, `startsWith`, and `containsPath`.
- Added extensive unit tests for the Pather class to ensure functionality and edge case handling.
- Updated Changelog and GithubChangelog plugins to utilize the new Pather utility for improved path handling in commit filtering.
These enhancements improve path management capabilities within the project, ensuring …
> [release-@qlover/fe-release-2.3.4 Release] Branch:master, Tag:2.3.4, Env:production

- packages/corekit-bridge/CHANGELOG.md
- packages/corekit-bridge/package.json
- 🏷️ Version: 1.3.1
- **corekit-bridge:** implement shallow clone utility and add tests for store state management ([fc596f3](https://github.com/qlover/fe-base/commit/fc596f33b91b3f457ab9d4c1e066b897c70c7f25)) ([#462](https://github.com/qlover/fe-base/pull/462))
- Introduced a `clone` utility for shallow cloning objects, arrays, and special instances (Date, RegExp, Set, Map).
- Added comprehensive tests for the `clone` function, ensuring correct behavior with various data types and structures.
- Implemented a `StoreInterface` with state management capabilities, including `resetState` and `cloneState` methods.
- Developed tests for `StoreInterface` to validate state initialization, cloning, and resetting functionality, ensuring robust state …
> [release-@qlover/corekit-bridge-1.3.1 Release] Branch:master, Tag:1.3.1, Env:production

- .vscode/settings.json
- eslint.config.js
- package.json
- pnpm-lock.yaml
- vite.config.ts
- Added 'make/**/*.{js,jsx,ts,tsx}' to ESLint file patterns for improved linting coverage.
- Included '@qlover/fe-release' in package.json dependencies to enhance project structure.
- Updated pnpm-lock.yaml to reflect the addition of '@qlover/fe-release'.
- Modified vite.config.ts to streamline exclusion patterns and improve clarity in file watching.
- Adjusted VSCode settings to refine vitest configuration search patterns.
These changes enhance the development environment and ensure better code quality across the project.
> chore: update ESLint configuration and package dependencies

- packages/corekit-bridge/__tests__/user-auth/impl/createState.test.ts
- packages/corekit-bridge/src/core/user-auth/impl/UserAuthState.ts
- packages/corekit-bridge/src/core/user-auth/impl/UserAuthStore.ts
- Added a new test case to verify that the login status is set to SUCCESS when both user info and credential are present.
- Updated the UserAuthState constructor to automatically set the login status to SUCCESS if user info and credential are provided.
- Improved documentation in UserAuthStore to clarify the behavior regarding login status.
These changes aim to improve the reliability of user authentication state handling and enhance test coverage.
> feat(corekit-bridge): enhance user authentication state management

- packages/create-app/CHANGELOG.md
- packages/create-app/package.json
- 🏷️ Version: 0.7.8
- **next-app:** enhance internationalization support with new localization files and refactor layout structure ([9d73643](https://github.com/qlover/fe-base/commit/9d7364337c18bac196a554b50e2342a51e15154d)) ([#506](https://github.com/qlover/fe-base/pull/506))
- Added English and Chinese localization files for common application messages to improve internationalization.
- Refactored layout.tsx to streamline locale handling and message retrieval using the new PageParams class.
- Removed the obsolete getServerI18n function to simplify the localization setup.
- Updated LoginPage and related components to utilize the new i18n structure for better translation handling.
These changes aim to enhance the user experience by providing …
> [release-@qlover/create-app-0.7.8 Release] Branch:master, Tag:0.7.8, Env:production

- packages/create-app/src/Generator.ts
- Modified the sourcePath in the copyPaths method to use a validated configPath, ensuring that the configuration file exists before proceeding with the copy operation. This change improves error handling and logging for missing configuration files.
These updates aim to enhance the reliability of the Generator class by preventing operations on non-existent paths.
> fix(generator): update config path handling in Generator class
